### ISSUE TITLE
State transition

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [LimeChain/hedera-services#153]
**Description:**
- `TokenCreateStateTransition` must be updated so that tokens of type `FUNGIBLE` & `NON_FUNGIBLE` can be created 
- For tokens of type `NON_FUNGIBLE` we should not issue the `initialSupply` to the treasury as it will always be `0`
- Implement Token NFT Creation (use Non-fungible Token store abstraction)"

**Comment by failfmi** [comment]
Did not find any changes that need to be made here.
