### ISSUE TITLE
Pre-check validations

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [LimeChain/hedera-services#159]
**Description:**
Update pre-check validations to check `amount` for `FUNGIBLE` tokens and to check `memo` size for `NON_FUNGIBLE` ones

**Comment by failfmi** [comment]
Amount check will probably be removed, because you will not know whether the op is for a `FUNGIBLE_COMMON` or `NON_FUNGIBLE_UNIQUE`

**Comment by Daniel-K-Ivanov** [comment]
Precheck -> `amount > 0` || atleast one `list of metadata`

**Comment by joan41868** [comment]
I think the check should be rewritten as:
```
// in order to mint nft, you need a 0 amount and at least x1 metadata
		boolean bothPresent = ( op.getAmount() > 0 && op.getMetadataCount() > 0 );
		boolean nonePresent = (op.getAmount() <= 0 && op.getMetadataCount() == 0);
		if ( bothPresent || nonePresent ) {
			return INVALID_TRANSACTION_BODY; // TODO which ResponseCodeEnum?
		}
```
