### ISSUE TITLE
Refactor Token Float changes

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [LimeChain/hedera-services#23]
The token float property must be changed in one of the following scenarios:
- Token Mint - when tokens are being minted the float must be increased (it may be implemented already)
- Token Burn - when tokens are being burned the float must be decreased (it may be implemented already)
- Token Wipe - when tokens are being wiped the float must be decreased

**Comment by failfmi** [comment]
It would be good to rename it to `totalAmount` for clarification.
