### ISSUE TITLE
Resolve outstanding issues with Besu Integration

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [LimeChain/hedera-services#296]
- [x] `MutableWorldStateImpl` should be deleted
- [ ] Account nonces -> Verify that account nonces can be always `0` and no side effects would come from that
- [ ] Implement `remove` method for the `AccountStateStore` in `ContractsStore`
- [ ] Implement `clearStorage` method for the `AccountStateStore` in `ContractsStore` -> Might not be supported from the VirtualMap atm
- [x] Change the `gasLimit` hardcoded property in `ContractCreateTransitionLogic` and `ContractCallTransitionLogic` to be retrieved from the global dynamic properties config. `StubbedBlockHeader` must have the same `gasLimit` as the one provided for the transaction (form the global dynamic properties)
- [x] Remove `blockHashLookup` argument from the `MainnetTransactionProcessor.processTransaction` method
- [x] `stubbedBlockHeader` -> The coinbase property must be the `txnCtx.submittingNodeAccount()`

**Comment by failfmi** [comment]
Closing this, tasks 2 - 4 have new issues - #339 and #347 respectively.
