### ISSUE TITLE
Updating Treasury on TokenUpdate operation

### ISSUE THREAD

**Issue by Petyo-Lukanov** [LimeChain/hedera-services#301]
At the moment if `TokenUpdate` is executed, that changes the `treasury` account of `Token` of type `FUNGIBLE_COMMON` we are:

- Changing the treasury account
- Transferring all `fungible tokens` from the previous treasury to the new one. This is performed efficiently by simply changing the balance of the old `treasury` and the new one. In terms of externalising there is a `TokenTransferList` with account amounts that reduce (from previous) and increase (to the new one) the token balance.

The goal is for `TokenUpdate` operation to be the same for tokens of type `NON_FUNGIBLE_UNIQUE` that means that we need to transfer all unique tokens (nfts) from the previous `treasury` to the new one. By definition nfts have unique representation. The straightforward approach (**that is not practical**) would mean iterating through all `unique tokens` for the given `Token` and changing the `owner` property. Since that is not practical, we came up with the following solution:

- If a given unique token is owned by the `treasury`, the owner property is represented as `0.0.0` in state.
- When querying unique tokens (`getTokenNftInfo`, `getTokenNftInfos`, `getAccountNftInfos`) we will be checking whether the owner is `0.0.0`, if it is, we will be populating the Token treasury
- When transferring `unique tokens`, if the transfer is `to` the treasury, the owner of the unique token (nft) will be set to `0.0.0`
The proposed change will enable us to do `TokenUpdate` operations that change the treasury of a `NON_FUNGIBLE_UNIQUE` token since we will be changing the `Token treasury` only and there won’t be a need for changing the owners of all unique tokens (nfts) since they will be set to `0.0.0`

Note: All queries/transfers and everything that is externalised in the transaction records will be populating the correct treasury account and no 0.0.0 will be externalised.

**Comment by daniel-danev-limechain** [comment]
https://www.notion.so/limechain/Token-Update-Diagram-09be0fdf8a1e477894b4f45c5f06c27f
