### ISSUE TITLE
Hedera Onboarding

### ISSUE THREAD

**Issue by Petyo-Lukanov** [LimeChain/hedera-services#318]
**Description:**

- [x] Create a Testnet account - portal.hedera.com
- [x] Go through overview information: hedera.com / https://www.youtube.com/c/HederaHashgraph/videos
- [x] Go through the development documentation - docs.hedera.com
- Focus on overview, introduction, concepts and transactions
- After you get familiar go through the guides using a preferred SDK (Java, Go, JS)
- Explore the different services - HTS, HCS, HFS, Scheduled TX)

**Comment by CordonaCodeCraft** [comment]
TestNet account created, awaiting for identity verification. 

![Screenshot](https://user-images.githubusercontent.com/77110630/124113701-6629a980-da74-11eb-8efa-87b4886eb80b.jpg)
