### ISSUE TITLE
Resolve Issue with many SSTORES/SLOADs

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [LimeChain/hedera-services#333]
With the previous `VirtualMap` we were having issues with executing many `SSTOREs`. It seemed that the hashing was freezing and the node stops processing transactions. When debugging it we discovered that the `Future` for hashing was not completing.

Goal:
Now that we have the new `VFCMap`, lets try to reproduce the issue and verify that it was resolved.

**Comment by failfmi** [comment]
The issue comes from the BinFile implementation. Will be resolved at a later stage, depending on the chosen data structure.
