### ISSUE TITLE
Compile the Onboarding pages in Notion

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [LimeChain/hedera-services#336]
Add all the information we have so far for the onboarding. Yoan and Ventsi prepared a framework; Everyone has a list of things that he has. Yoan has diagram for the merkle tree. Radi has E2E tests.

The task is to compile the information, get it from everyone and place it in the notion file:
https://www.notion.so/limechain/Hedera-Core-Development-e0340dd9c76148c6863a99e91d2a1005

Add different pages for the different steps. It must be easy to follow from a new colleague

**Comment by Petyo-Lukanov** [comment]
Some minor edits are left to be implemented for the current version. The improvement of the onboarding document will remain a background, continuous tasks.
