### ISSUE TITLE
Unit Test Coverage

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [LimeChain/hedera-services#338]
Coordinate and work on increasing the unit test coverage of `Hedera Services`

- [ ] FeeCalcUtils
- [ ] GetVersionInfoResourceUsage
- [ ] HFileMetaSerde
- [ ] HederaKeyActivation (keys package)
- [ ] TransactionRecordService
- [ ] AccountBalance
- [ ] SignedStateBalancesExporter
- [ ] MerkleEntityAssociation
- [ ] RecordsRunningHashLeaf

**Comment by Petyo-Lukanov** [comment]
Closing this ticket as the effort will be handled in - https://github.com/limechain/hedera-services/issues/332
Regards, 
Petyo
