### ISSUE TITLE
Smart Contract Creation

### ISSUE THREAD

**Issue by Petyo-Lukanov** [LimeChain/hedera-services#340]
Goal:
Make sure that the Besu Integration supports smart contracts creating new smart contracts. Keep in mind that the newly created contracts (deployed through factories) must have proper `contractIDs` set. The only way for us to set correct IDs is to request Hedera to generate the IDs for us.

`CREATE` and `CREATE2` opcodes must be refactored such that, the newly created contract must have a predetermined by Hedera  - ID

For the successful completion of the issue, we need to have E2E tests that trigger both CREATE and CREATE2 and verify the newly created smart contract and its ID

**Comment by Daniel-K-Ivanov** [comment]
CREATE2 - maybe we should not support it since it is going to be misleading

**Comment by Petyo-Lukanov** [comment]
To review
