### ISSUE TITLE
Throttling based on gas limit, rather than ops/sec 

### ISSUE THREAD

**Issue by Petyo-Lukanov** [LimeChain/hedera-services#360]
Research on throttling based on gas price, rather than ops/sec

**Comment by stoqnkpL** [comment]
Research doc in notion: https://www.notion.so/limechain/Throttling-by-gas-research-65d82ac2e30a43768a603e7f89850a9e

**Comment by Daniel-K-Ivanov** [comment]
@Daniel-K-Ivanov schedule a call tmr
