### ISSUE TITLE
CryptoCreate Refactoring

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [LimeChain/hedera-services#366]

**Comment by joan41868** [comment]
Quick overview:

In the `CryptoCreateTransitionLogic` you'll find `ledger.create(....)` method, which:
 - creates a new account in the `TransactionalLedger`  - `spawn` -> `accountsLedger.create()`
 - computes and adjusts the balance of the `sponsor` account - `computeNewBalance`
 - computes and adusts the balance of the new account 
 - updates the transfers on both - reducing sponsor balance and increasing the new account balance - `updateXfers`
 - customizes the new account 
 
 Problems:
 You need to "mimic" this behaviour in `Account` and `AccountStore` classes. However, `HederaLedger` should still be responsible of the transfer logic, i.e. - modifying the transfer lists. 
 Backward compatibility - you will refactor only `CryptoCreate`, but `CryptoDelete` depends on those changes.
 
 Potential solutions:
  - Move the `TransactionalLedger<AccountID, AccountProperty, MerkleAccount> accountsLedger` in `AccountStore` . Problem - there's already a DS with (i think) the same responsibility. 
  - Maintain backwards compatibility via `@FunctionalInterface`s - `accountsLedger.create`, `updateXfers`, `computeBalance`, etc. 
  
  
  Feel free to comment below with better solutions :)
