### ISSUE TITLE
Introduce Uint 256 support 

### ISSUE THREAD

**Issue by Petyo-Lukanov** [LimeChain/hedera-services#383]
The current implementation of `ContractUint256` has support only for `long` and not `uint256` as the name states. This class is used by the data structure (map) as `key` and `values` for the map. 

On the other hand, in the `DefaultMutableStateUpdater`, the EVM is using apache's `Uint256` class to store contract's key/value pairs and on commit we are "translating" the bytes from `UInt256` to the class that implements the virtual map key/value pairs -> `ContractUint256`.

This tasks requires us to modify or create a brand new `ContractUint256` class that:

1. Implements the `VirtualKey` and `VirtualValue` interfaces in order for us to use it in the virtual maps
2. Supports `uint256` values not only `long`
3. Transfers the values/bytes from apache's `Uint256`  implementation into its own class as efficiently as possible

After the implementation is complete, we must test it with key/values that are bigger than long and verify that the virtual map is storing them correctly

**Comment by Daniel-K-Ivanov** [comment]
Will be addressed after Wednesday
