### ISSUE TITLE
Cleanup Smart Contract E2E tests

### ISSUE THREAD

**Issue by Petyo-Lukanov** [LimeChain/hedera-services#385]
Current e2e tests related to smart contracts are outdated or simply failing. This issue aims to refactor and remove the unnecessary legacy code from those tests.
The tests are located at `test-clients/src/main/java/bdd/suites/contract/`. We can see that there are a lot of tests. 

1. Revise existing e2e tests. Execute them and determine whether some of them must be deleted or not. Compile a list of the failing tests and add it as comment here. We must be sure that failing tests are failing correctly and on purpose we are deciding that we won't support such use-cases OR we must act based on the failing tests and resolve issues with our Integration
2. Once the already existing list of tests has been revised; all issues have been resolved and unnecessary tests are removed, we can introduce our own tests. Atm we are placing everything inside `ContractCallSuite` and the majority of the tests are commented. We must extract different types of tests into different files as-well as make sure that all tests can be uncommented and get them to pass.

**Comment by rusiboyadjiev** [comment]
**Not working tests:**

BenchmarkStoreSpec
    -benchmarkSingleSetter(), //failing due to lack of uint256 support
    -benchmarkLoadTx(), //failing due to lack of uint256 support
    -benchmarkNCreations(), //failing due to lack of uint256 support
    -benchmarkNCreationsWithUpdates(), //failing due to lack of uint256 support
    -benchBigSSTORE(), //failing due to lack of uint256 support
    -SSTORE() //failing due to lack of uint256 support

InsufficientSpec
    -lowBalanceFails //skip to the completion of support smart contract factory development
    -undersizedMaxResultFails //skip to the completion of support smart contract factory development
    -impureCallFails //skip to the completion of support smart contract factory development
    -insufficientFeeFails //skip to the completion of support smart contract factory development
    -rejectsInsufficientGas
    -rejectsInvalidBytecode
    -revertsNonzeroBalance

SmartContractFailFirstSpec
    -smartContractFailFirst

InvalidSpec
    -invalidAbi //skip to the completion of support smart contract factory development
    -invalidCallReceiverAccount
	-invalidDelegateCallReceiverAccount
	-invalidStaticCallReceiverAccount

PayableSpec
    -payableSuccess //skip to the completion of support smart contract factory development
    -nonPayable //skip to the completion of support smart contract factory development

ContractGetRecordsSuite
    -recordsExpire
    -vanillaSuccess

ChildStorageSpec
    -childStorage

SmartContractSelfDestructSpec
    -payTestSelfDestructCall

ContractCallLocalSuite
    -vanillaSuccess //skip to the completion of support smart contract factory development

ContractCallSuite
    -vanillaSuccess //skip to the completion of support smart contract factory development

ContractGetBytecodeSuite
    -vanillaSuccess

NewOpInConstructorSuite
    -contractCreateWithNewOpInConstructor - ChildStorage
    -contractCreateWithNewOpInConstructor - AbandoningParent

OCTokenSpec
    -ocToken

SmartContractInlineAssemblySpec
    -smartContractInlineAssemblyCheck
