### ISSUE TITLE
SmartContract Factory + Non existing account bug

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [LimeChain/hedera-services#419]
We have a use case for exceptional halt reason due to INVALID_SOLIDITY_ADDRESS in contract create transition logics as-well. If a contract tries to do anything to another contract in its constructor, we will interact with non-existing account

**Comment by Daniel-K-Ivanov** [comment]
sending `value=0` to account with no code might be a no-op

**Comment by Petyo-Lukanov** [comment]
To review
