### ISSUE TITLE
Ensure token delete checks on deleted Token

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [LimeChain/hedera-services#45]
Once deleted update, mint, burn, wipe, freeze, unfreeze, grant kyc, revoke kyc and token transfer transactions must resolve to TOKEN_WAS_DELETED

**Comment by failfmi** [comment]
Update:
Token Update - not checked
Mint/burn - checked
Freeze/unfreeze - checked
Grant/Revoke KYC - checked
Transfer - checked

**Comment by georgiyazovaliiski** [comment]
Added check for Update + unit and bdd tests
