### ISSUE TITLE
Research - Freeze/Unfreeze/Wipe on token which does not exist

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [LimeChain/hedera-services#46]
What is the result of performing Freeze/unfreeze/wipe etc operations on token that does NOT exist.

**Comment by failfmi** [comment]
Checks for existence and deletion are made, plus an association check between the target account & token is done as well.

**Comment by failfmi** [comment]
Checks for existence and deletion are made, plus an association check between the target account & token is made as well.

**Comment by Daniel-K-Ivanov** [comment]
I think that it will be useful to update the HAPI Docs with detailed explanation on when/what response codes are returned on Freeze/Unfreeze/Wipe when:
- token does not exist
- token is deleted
