### ISSUE TITLE
Implement `TransferLogic`

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [LimeChain/hedera-services#685]
Reference -> https://github.com/hashgraph/hedera-services/issues/2416

Start with local branch in LimeChain -> `feat/transfer-logic`

**Comment by Daniel-K-Ivanov** [comment]
![image](https://user-images.githubusercontent.com/12232750/140885254-7df58ded-020d-4e23-9d09-5a7732baaa0c.png)

**Comment by Petyo-Lukanov** [comment]
**PR:** https://github.com/hashgraph/hedera-services/pull/2497
