### ISSUE TITLE
HSCS-PREC-017 [Precompile Rollbacks] after insufficient balance

### ISSUE THREAD

**Issue by stoqnkpL** [LimeChain/hedera-services#729]
https://github.com/hashgraph/hedera-services/issues/2477

Verify a precompile transfer with custom fees that fails because a preceding Solidity .transfer() in the same frame depleted a custom ℏ fee payer's balance has no effects no state (and the preceding transfer() is also reverted).

**Comment by Petyo-Lukanov** [comment]
PR: https://github.com/hashgraph/hedera-services/pull/2590
