### ISSUE TITLE
Include Contract function result in child record

### ISSUE THREAD

**Issue by Petyo-Lukanov** [LimeChain/hedera-services#730]
- `contractID` → Address of `precompile`
-  `contractCallResult` -> return bytes (e.g `serialNumbers` minted or `newTotalSupply`)
- `errorMessage` -> not populated
- `bloom` → not populated
- `gasUsed` → what we charged (`10_000` for all calls for now)
- `logInfo` → not populated for now. When we have erc20 equivalence, events will be populated there
- `createdContractIDs` → will not be populated

**Comment by stoqnkpL** [comment]
Populate `errorMessage` in `ContractCallResult` when the precompile fails
