### ISSUE TITLE
Investigate Failing EETs in hts-contracts

### ISSUE THREAD

**Issue by stoqnkpL** [LimeChain/hedera-services#781]
- [ ] GetInfoWorks
- [ ] childCreationsHaveExpectedKeysWithOmittedAdminKey
- [ ] txRecordsContainValidTransfers
- [ ] CreateOperationSuite
- [ ] HSCS_EVM_008_SelfDesctructUpdatesHederaAccount

**Comment by Daniel-K-Ivanov** [comment]
Problem was with self destruct
