### ISSUE TITLE
[HIP-358 Token Create] Implement TokenUpdateLogic

### ISSUE THREAD

**Issue by stoqnkpL** [LimeChain/hedera-services#860]
In order to allow updating tokens through the HTS precompile, we will need a `TokenUpdateLogic` similar to the `TransferLogic`, `MintLogic`, `BurnLogic`, etc.
We need to be able to instantiate it with the current Updater's `TransactionalLedgers` and track/commit/revert the updates in the context of an EVM transaction.

- [ ] Research token update current implementation
- [ ]  Implement `TokenUpdateLogic`
- [ ]  Refactor `TokenUpdateTransitionLogic` to work with the new `TokenUpdateLogic`

**Comment by mustafauzunn** [comment]
https://github.com/LimeChain/hedera-services/tree/precompiles/token-update
