### ISSUE TITLE
Implement logic for achieving atomicity for h-bar transfers #2864

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [LimeChain/hedera-services#861]
Improve atomicity of state changes and records construction for h-bar. transfers. Implement common EntityChanges record and specific interceptor classes for each ledger type to track and validate all accumulated changes in the moment prior to TransactionalLedger.commit()

E.g.

H bar transfer:

 Improve atomicity of account state changes (account's BALANCE property) and record transfer list construction.
 We should make (1) changing a balance field in a Merkle leaf and (2) updating a record transfer list atomic.

**Comment by Petyo-Lukanov** [comment]
PR: https://github.com/hashgraph/hedera-services/pull/2886
